schema_version = "1.0.0"

id = "blender_resonite_sdk"
version = "0.0.1"
name = "Resonite SDK"
tagline = "Resonite SDK for Blender"
maintainer = "JackTheFoxOtter"
type = "add-on"

website = "https://github.com/JackTheFoxOtter/blender-resonite-sdk/"
tags = [
    "Game Engine", 
    "Import-Export", 
    "Pipeline" 
]

blender_version_min = "5.1.0" # ResoniteLink.py targets Python 3.13, which is only available in Blender 5.1.0 and upwards.

license = [
    "SPDX:GPL-3.0-or-later",
]

wheels = [
    "./wheels/llvmlite-0.47.0-cp313-cp313-win_amd64.whl",
    "./wheels/numba-0.65.1-cp313-cp313-win_amd64.whl",
    "./wheels/quaternionic-1.0.17-py3-none-any.whl",
    "./wheels/resonitelink_py-0.1.0b97-py3-none-any.whl",
    "./wheels/scipy-1.17.1-cp313-cp313-win_amd64.whl",
    "./wheels/websockets-16.0-cp313-cp313-win_amd64.whl",
]

[permissions]
network = "Connect to Resonite via ResoniteLink (usually via local network)"

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "/.git/",
    "/*.zip",
]
